// SPDX-FileCopyrightText: 2026 Universitas Sriwijaya
// SPDX-License-Identifier: GPL-3.0-or-later

`default_nettype none

// DE10-Nano top level for RO-PUF characterization.
//
// char_sys is generated by Platform Designer from char_sys.tcl: a JTAG to
// Avalon master bridge driving the SIDIK RO-PUF core (rtl/ropuf/ropuf_avmm.v,
// which contains ro_array + puf_meas) at base address 0x0. System Console
// talks to it through the USB-Blaster II (fpga/char/syscon/measure_pairs.tcl).
//
// KEY[0] resets the system (active low). LED[0] blinks at ~1.5 Hz while the
// 50 MHz clock runs; LED[1] is on while the system is out of reset.
module sidik_char_top (
    input  wire       FPGA_CLK1_50,
    input  wire [1:0] KEY,
    output wire [7:0] LED
);

    wire clk = FPGA_CLK1_50;

    // Asynchronous assert, synchronous release.
    reg [1:0] rst_n_sync;
    always @(posedge clk or negedge KEY[0]) begin
        if (!KEY[0])
            rst_n_sync <= 2'b00;
        else
            rst_n_sync <= {rst_n_sync[0], 1'b1};
    end

    char_sys u_sys (
        .clk_clk       (clk),
        .reset_reset_n (rst_n_sync[1])
    );

    reg [24:0] heartbeat;
    always @(posedge clk)
        heartbeat <= heartbeat + 1'b1;

    assign LED = {6'b0, rst_n_sync[1], heartbeat[24]};

endmodule

`default_nettype wire
